AprendeTEA_19032025/Models/Admin.cs
using System.ComponentModel.DataAnnotations;

namespace AprendeTEA_19032025.Models
{
    public class Admin
    {
        [Key]
        public int IdAdmin { get; set; }

        [Required(ErrorMessage = "El correo electronico es obligatorio")]
        public string Email { get; set; }
    }
}

AprendeTEA_19032025/Models/ErrorViewModel.cs
namespace AprendeTEA_19032025.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AprendeTEA_19032025/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace AprendeTEA_19032025.Models
{
    public class User
    {
        [Key]
        public int IdUser { get; set; }

        [Required(ErrorMessage = "El correo electronico es obligatorio")]
        public string Email { get; set; }
        [Required(ErrorMessage = "La contraseña es obligatoria")]
        public string Pass { get; set; }
    }
}

AprendeTEA_19032025/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AprendeTEA_19032025.Models;

namespace AprendeTEA_19032025.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AprendeTEA_19032025/Controllers/LeccionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AprendeTEA_19032025.Controllers
{
    public class LeccionController : Controller
    {
        // GET: LeccionController
        public ActionResult Lecciones()
        {
            return View();
        }

        // GET: LeccionController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LeccionController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeccionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LeccionController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LeccionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LeccionController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LeccionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AprendeTEA_19032025/Controllers/PerfilController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AprendeTEA_19032025.Controllers
{
    public class PerfilController : Controller
    {
        // GET: PerfilController
        public ActionResult MiPerfil()
        {
            return View();
        }

        // GET: PerfilController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PerfilController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PerfilController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PerfilController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PerfilController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PerfilController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PerfilController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AprendeTEA_19032025/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Aprende TEA";
}
<br />
<br />

<div class="container">
    <!-- Título del reporte -->
    <div class="text-center">
        <h1 class="display-4" style="background-color: #729BFF; padding: 20px; border-radius: 8px;">Aprende TEA</h1>
    </div>

    <br />

    <!-- Sección de párrafos -->
    <div>
        <p style="font-size: 18px; line-height: 1.6; text-align: justify;">
            El Trastorno del Espectro Autista (TEA) es una condición del neurodesarrollo que afecta la comunicación, el comportamiento y la interacción social. Aunque los desafíos varían entre individuos, existen herramientas que pueden ayudar a las personas con TEA a alcanzar su máximo potencial.
        </p>
        <p style="font-size: 18px; line-height: 1.6; text-align: justify;">
            Este reporte busca educar y sensibilizar sobre el TEA, explorando estrategias de enseñanza inclusivas y recursos disponibles para apoyar a quienes forman parte de este espectro. Aprender más sobre el TEA es un paso hacia la creación de una sociedad más empática y comprensiva.
        </p>
    </div>

    <br />

    <!-- Sección de imágenes -->
    <div class="row text-center">
        <div class="col-md-4">
            <img src="../img/biblioteca.jpg" alt="Biblioteca" class="img-fluid" style="border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
            <p style="margin-top: 10px;">Un espacio para el aprendizaje inclusivo.</p>
        </div>
        <div class="col-md-4">
            <img src="../img/biblioteca.jpg" alt="Aprendizaje" class="img-fluid" style="border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
            <p style="margin-top: 10px;">Herramientas educativas accesibles.</p>
        </div>
        <div class="col-md-4">
            <img src="../img/biblioteca.jpg" alt="Sociedad inclusiva" class="img-fluid" style="border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
            <p style="margin-top: 10px;">Hacia una sociedad empática.</p>
        </div>
    </div>

    <br />

    <!-- Conclusión -->
    <div>
        <p style="font-size: 18px; line-height: 1.6; text-align: justify;">
            Al conocer más sobre el TEA y sus características, podemos convertirnos en agentes de cambio para las personas en este espectro. La inclusión comienza con el entendimiento, y tú puedes ser parte de este movimiento.
        </p>
    </div>
</div>

<br />
<br />

AprendeTEA_19032025/Views/Leccion/Lecciones.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />

AprendeTEA_19032025/Views/Perfil/MiPerfil.cshtml
@{
    ViewData["Title"] = "Mi Perfil";
}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="text-center">
    <h1 class="display-4">Perfil</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />

AprendeTEA_19032025/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AprendeTEA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    @* <link href="~/css/GeneralClaro.css" rel="stylesheet" /> *@
    <link href="~/css/GeneralObscuro.css" rel="stylesheet" />
    <link href="~/css/footer.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <header>
        <div class="glowing">

            <span style="--i:1;"></span>

            <span style="--i:2;"></span>

            <span style="--i:3;"></span>

        </div>

        <div class="glowing">

            <span style="--i:1;"></span>

            <span style="--i:2;"></span>

            <span style="--i:3;"></span>

        </div>

        <div class="glowing">

            <span style="--i:1;"></span>

            <span style="--i:2;"></span>

            <span style="--i:3;"></span>

        </div>

        <div class="glowing">

            <span style="--i:1;"></span>

            <span style="--i:2;"></span>

            <span style="--i:3;"></span>

        </div>
        <div class="navigation">
            <div class="menuToggle"></div>
            <ul>
                <li class="list @(ViewContext.RouteData.Values["action"].ToString() == "Index" ? "active" : "")" style="--clr: #f44336">
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        <span class="icon"><ion-icon name="home-outline"></ion-icon></span>
                        <span class="text">Inicio</span>
                    </a>
                </li>
                <li class="list @(ViewContext.RouteData.Values["action"].ToString() == "Privacy" ? "active" : "")" style="--clr: #ffa117">
                    <a asp-area="" asp-controller="Home" asp-action="Privacy">
                        <span class="icon"><ion-icon name="book-outline"></ion-icon></span>
                        <span class="text">Lecciones</span>
                    </a>
                </li>
                <li class="list @(ViewContext.RouteData.Values["action"].ToString() == "Progreso" ? "active" : "")" style="--clr: #0fc70f">
                    <a href="#">
                        <span class="icon"><ion-icon name="trophy-outline"></ion-icon></span>
                        <span class="text">Progreso</span>
                    </a>
                </li>
                <li class="list @(ViewContext.RouteData.Values["action"].ToString() == "MiPerfil" ? "active" : "")" style="--clr: #2196f3">
                    <a asp-area="" asp-controller="Perfil" asp-action="MiPerfil">
                        <span class="icon"><ion-icon name="person-outline"></ion-icon></span>
                        <span class="text">Perfil</span>
                    </a>
                </li>
                <li class="list @(ViewContext.RouteData.Values["action"].ToString() == "Configuracion" ? "active" : "")" style="--clr: #b145e9">
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="settings-outline"></ion-icon>
                        </span>
                        <span class="text">Configuración</span>
                    </a>
                </li>
            </ul>

        </div>
    </header>
    <div class="container" style="margin-left: 12%">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @* <div>&copy; 2024 - AprendeTEA_V1._0 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></div> *@
            <div id="social-footer">
                <ul>
                    <li>
                        <a href="#"> <i class="fab fa-facebook-f icon"></i> </a>
                    </li>
                    <li>
                        <a href="#"><i class="fab fa-twitter icon"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fab fa-linkedin-in icon"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fab fa-google-plus-g icon"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fab fa-whatsapp icon"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fab fa-github icon"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fab fa-youtube icon"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="module"
            src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule
            src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="~/js/Navbar.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>